# Generated by Django 4.1.7 on 2023-03-29 16:13

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBlockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Підзаголовок')),
            ],
            options={
                'verbose_name': 'Налаштування блоку "Про нас"',
            },
        ),
        migrations.CreateModel(
            name='ContactsBlockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_address', models.CharField(max_length=64, verbose_name='Юридична адреса')),
                ('contact_center_wh', models.CharField(max_length=64, verbose_name='Графік роботи контактного центру')),
                ('administration_wh', models.CharField(max_length=64, verbose_name='Графік роботи адміністрації')),
                ('phone_numbers', models.TextField(verbose_name='Телефони для звернень')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Налаштування блоку "Контактні дані"',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Назва')),
                ('file', models.FileField(upload_to='documents', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="Ім'я")),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='partners', verbose_name='Зображення')),
                ('url', models.URLField(verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Партнера',
                'verbose_name_plural': 'Партнерів',
            },
        ),
        migrations.CreateModel(
            name='WelcomeBlockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('subtitle', models.TextField(max_length=512, verbose_name='Підзаголовок')),
            ],
            options={
                'verbose_name': 'Налаштування головного блоку',
            },
        ),
    ]
