# Generated by Django 4.1.7 on 2023-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusblocksettings',
            options={'verbose_name': '2. Налаштування блоку "Про нас"'},
        ),
        migrations.AlterModelOptions(
            name='contactsblocksettings',
            options={'verbose_name': '5. Налаштування блоку "Контактні дані"'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': '4. Документи'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнера', 'verbose_name_plural': '3. Партнери'},
        ),
        migrations.AlterModelOptions(
            name='welcomeblocksettings',
            options={'verbose_name': '1. Налаштування головного блоку'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=64, verbose_name="Ім'я"),
        ),
    ]
